version: '3'
networks:
  pix-network:
    driver: bridge
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - pix-network
    environment:
      POSTGRES_PASSWORD: root
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
    networks:
      - pix-network
    depends_on:
      - postgres
  itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091
    networks:
      - pix-network
    depends_on:
      - bcb
  grpc-pix:
    image: grpc-pix:latest
    ports:
      - 50051:50051
    networks:
      - pix-network
    environment:
      DB_URI: jdbc:postgresql://postgres:5432/postgres?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: postgres
      DB_PASSWORD: root
      DB_DIALECT: POSTGRES
      ITAU_URL: http://itau:9091
      BCB_URL: http://bcb:8082
    depends_on:
      - itau