micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: jdbc:${DB_SERVER:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DATABASE_DB:pix}?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.show_sql: false
      hibernate.format_sql: false

itau.client.url: http://${ITAU_HOST:localhost}:9091

bcb.client.url: http://${BCB_HOST:localhost}:8082