micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/pix?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD:root}
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.show_sql: true
      hibernate.format_sql: true

itau:
  contas:
    url: 'http:\\localhost:9091'
