micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&serverTimezone=UTC`}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    schema-generate: CREATE
    dialect: ${DB_DIALECT:POSTGRES}

jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: create
      hibernate.show_sql: true
      hibernate.format_sql: true

itau.client.url: ${ITAU_URL:`http://localhost:9091`}

bcb.client.url: ${BCB_URL:`http://localhost:8082`}